version: '3.8'

services:
  redis:
    image: redis:latest
    container_name: wanderer_redis
    ports:
      - "6380:6379"
    volumes:
      - wanderer_redis_data:/data
  
  redisinsight:
    image: redislabs/redisinsight:latest
    container_name: redis-insight
    ports:
      - "5540:5540"

volumes:
  wanderer_redis_data:
